- role: Research Assistant
  location: LSU
  note: supervised by Dr. Chen Wang 
  year: 2022 - Present

- role: Teaching Assistant
  location: LSU
  note: grading and lab teaching
  year: 2021 - Present

- role: High School Summer Research (HSSR) Speaker
  location: LSU
  note:  
  year: 2023

- role: HighSchool Summer Research (HSSR) Poster Judge
  location: LSU
  note: 
  year: 2022
