name: Build and Deploy Jekyll site with Jekyll-Scholar

on:
  push:
    branches:
      - main  # or master depending on your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'  # adjust the Ruby version if needed

    - run: gem install bundler
    - run: bundle install
    - run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site